# Generated by Django 5.0.6 on 2024-07-24 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='auction_listings',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='reference',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.auction_item'),
            preserve_default=False,
        ),
    ]
