# Generated by Django 5.2 on 2025-04-13 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_item_delete_auction_listings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='auction_item',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=100)),
                ('P_descr', models.CharField(max_length=700)),
                ('P_bid', models.IntegerField()),
                ('P_image', models.CharField(max_length=700)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Auction_item',
        ),
        migrations.DeleteModel(
            name='bids',
        ),
    ]
